#ifndef ERROR_H
#define ERROR_H

typedef enum {
	SUCCESS = 0,
	ERR_SRC_EMPTY,
	ERR_DST_OCCUPIED,
	ERR_PMP_OCCUPIED,
	ERR_PMP_USED,
	ERR_PMP_UNUSED,
	ERR_INVALID_CSLOT,
	ERR_INVALID_REGISTER,
	ERR_INVALID_PMPIDX,
	ERR_INVALID_DERIVATION,
	ERR_INVALID_CAPTY,
	ERR_MON_INVALID_PID,
	ERR_INVALID_SYSCALL,
	PREEMPTED = -1,
	INTERFERENCE = -2
} error_t;

#endif /* ERROR_H */
