name: Clang Format Checker
on: [push]
jobs:
  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install clang-format
      - run: clang-format -Werror --dry-run $(find -regextype sed -regex ".*\.\(c\|cc\|h\)")
