name: Google Test
on: [push]
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install gtest
        run: >
          sudo apt-get install libgtest-dev && 
          cd /usr/src/gtest && 
          sudo cmake CMakeLists.txt && 
          sudo make && 
          sudo cp lib/*.a /usr/lib && 
          sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && 
          sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
      - name: Make tests
        run: make -C test
      - name: Run tests
        run: ./test/test_cap.out
